---
- hosts: all

  tasks:
    - name: Include network specific vars
      ansible.builtin.include_vars: network.yml
      tags: [always]

    - name: Include main vars
      ansible.builtin.include_vars: main.yml
      tags: [always]

    - name: Include default vars
      ansible.builtin.include_vars: defaults/main.yml
      tags: [always]

    - name: Include task osmosis
      include_tasks: tasks/osmosis.yml
      tags: osmosis

    - name: Include task monitoring
      include_tasks: tasks/monitoring.yml
      tags: monitoring  
