---
- name: Task Run Cosmos Validator Watcher Container
  docker_container:
    name: cosmos-validator-watcher
    image: "{{ kiln_monitoring_image }}"
    state: started
    auto_remove: false  # Ensure the container is not removed after it stops
    network_mode: host
    command: "--node https://osmosis-testnet-rpc.polkachu.com:443 \
              --node http://localhost:26657 \
              --validator 8E9C454C7483D0C05A93B6C005B50C47958913B1:nodes.club"
    env:
      SERVICE_SCHEME: http
      SERVICE_HOST: "localhost"
    detach: true
