---
- name: Task copy config.yml
  become_user: root
  become: true
  template:
    src: config.yml
    dest: "{{ tendermint_host_config_mount }}/config.yml"
    force: true
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - config.yml

# Validator docker ports
- name: Task Set tenderduty docker ports
  set_fact:
    docker_tenderduty_ports: "{{ tenderduty_docker_ports }}"

- name: Task Run Tenderduty Validator Watcher Container
  docker_container:
    name: tenderduty
    image: "{{ tenderduty_monitoring_image }}"
    state: started
    restart_policy: unless-stopped
    auto_remove: false  # Ensure the container is not removed after it stops
    networks:
      - name: "osmosis-validator-net"
    ulimits:
      - nofile:65535:65535
    networks_cli_compatible: true
    command: ""
    detach: true
    ports: "{{ docker_tenderduty_ports }}"
    volumes:
      - "{{ tendermint_host_config_mount }}/tenderduty:/var/lib/tenderduty"
      - "{{ tendermint_host_config_mount }}/config.yml:/var/lib/tenderduty/config.yml"
